language: go
sudo: required
go:
  - 1.7
env:
  global:

before_script:
  - sleep 1

services:
  - docker

before_install:

script:
  - go get ./...
  - ( cd server/ && go build -o PowerController )

after_success:
  - cd server
  - sudo docker login -u gregdistefano -p $DOCKER_PASSWORD
  - sudo docker build -t gregdistefano/powercontroll .
  - sudo docker tag gregdistefano/powercontroll gregdistefano/powercontroll:latest 
  - sudo docker push gregdistefano/powercontroll:latest 
